data:
  dataset: lego

model:
  nerf_kwargs:
    D: 8
    W: 256
    num_pts_octaves: 10
    start_pts_octave: 0
    num_view_octaves: 4
    start_view_octave: 0
    
training:
  batch_size: 1
  ray_size: 1024
  peak_lr: 5e-4
  peak_it: 0
  decay_rate: 0.1
  decay_it: 500000
  N_coarse_samples: 64
  N_fine_samples: 128
  precrop_iters: 500
  precrop_frac: 0.5