
model:
  nerf_kwargs:
    D: 8
    W: 256
    num_pts_octaves: 10
    start_pts_octave: 0
    num_view_octaves: 4
    start_view_octave: 0
  objemb_kwargs:
    num_obj: 2
N_coarse_samples: 64
N_fine_samples: 128
precrop_iters: 500
precrop_frac: 0.5


training:
  num_workers: 12
  batch_size: 1024
  max_it: 4000000
  decay_it: 4000000
  lr_warmup: 2500